### ISSUE TITLE
List of functions that should be in 1.0.0

### ISSUE THREAD

**Issue by jaapz** [elm-community/string-extra#1]
- [x] decapitalize
 - [x] classify
 - [x] camelize
 - [x] isBlank
 - [x] clean
 - [x] softBreak
 - [x] break
 - [x] insertAt
 - [x] replaceSlice
 - [x] replace
 - [x] toTitleCase
 - [x] toSentenceCase
 - [ ] cleanDiacritics
 - [x] countOccurances
 - [x] wrap
 - [x] wrapWith
 - [x] softWrap (missing tests)
 - [x] softWrapWith (missing tests)
 - [x] humanize
 - [x] dasherize
 - [x] underscored
 - [x] unindent
 - [x] truncate
 - [x] softTruncate (missing tests)
 - [x] ~~strRight~~ rightOf (missing tests)
 - [x] ~~strRightBack~~ rightOfBack (missing tests)
 - [x] ~~strLeft~~ leftOf (missing tests)
 - [x] ~~strLeftBack~~ leftOfBack (missing tests)
 - [x] stripTags (missing tests)
 - [x] toSentence (missing tests)
 - [x] toSentenceOxford (missing tests)
 - [x] surround
 - [x] unsurround
 - [x] quote
 - [x] unquote
 - [ ] slugify
 - [ ] naturalCompare

**Comment by jaapz** [comment]
@lorenzo i copied the list from the slack channel to here so we can keep track of what's done and what still needs to be done

**Comment by lorenzo** [comment]
Thanks, good idea

**Comment by jvoigtlaender** [comment]
It's not clear from the listed function names, so I guess I'd best ask:

How about the two functions currently in https://github.com/elm-community/elm-string-split, namely `chunksOfLeft : Int -> String -> List String` and `chunksOfRight : Int -> String -> List String`?

**Comment by lorenzo** [comment]
@jvoigtlaender `chunksOfLeft` is named `break` in this repo... I'm not sure if there is an actual use case for `chunksOfRight` but I'd be happy to include it if there is one

**Comment by lorenzo** [comment]
I'll take the liberty of closing this ticket. The majority of functions are already implemented, and only those that need to deal with different collations of special characters are left out. They are maybe good material for another package.
