### ISSUE TITLE
Update to Latest Version of Elm Test

### ISSUE THREAD

**Issue by prikhi** [elm-community/string-extra#19]
#18 Mentioned that tests are failing with the latest version of elm-test. Tests should be updated to work with the latest version.

There is a pretty big slowdown in 0.18.4, so `.travis.yml` should be updated to also use `sysconfcpus` when running `elm-test`(instead of just for the `elm-make` call).

@lorenzo @jaapz - any preference if we should stick to fixing the elm-test version or make it unbounded?

**Comment by jaapz** [comment]
I prefer keeping a fixed version and just update it every once in a while. I've personally had too many breaking things when allowing more lenient version specifiers.

**Comment by lorenzo** [comment]
Better keep the version fixed.

If anyone wants to fix the tests to run in the latest version, then we can pin to that one

**Comment by prikhi** [comment]
Started on this but getting a couple of crashes in `Fuzz.Internal`:
https://travis-ci.org/elm-community/string-extra#L863
