### ISSUE TITLE
Simple Replace function

### ISSUE THREAD

**Issue by Chadtech** [elm-community/string-extra#34]
Hi,

I use this function a lot.

```elm
replace : String -> String -> String -> String
replace target replacement str =
    str
        |> String.split target
        |> String.join replacement
```

Ive used it to replace spaces with underscores, and to replace `%2F` with `/` when decoding urls inside json.

Would this be a good addition to `String.Extra`?

**Comment by lorenzo** [comment]
It already exists in the core String module, see https://github.com/elm-community/string-extra/pull/33

**Comment by Chadtech** [comment]
Oops. Okay then. No need.
